### ISSUE TITLE
Numpy dependency missing

### ISSUE THREAD

**Issue by GearsAD** [rdeits/DrakeVisualizer.jl#35]
Hi,

When installing via Pkg.add("DrakeVisualizer") in Julia, seems the numpy dependency is missing?

Thanks,
Sam
cc @dehann 

```bash
gearsad@gearsad-Surface-Pro-3:~/.julia/v0.5/DrakeVisualizer/deps/usr/bin$ ./drake-visualizer 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/gearsad/.julia/v0.5/DrakeVisualizer/deps/usr/lib/python2.7/dist-packages/director/drakevisualizerapp.py", line 3, in <module>
    from director import mainwindowapp
  File "/home/gearsad/.julia/v0.5/DrakeVisualizer/deps/usr/lib/python2.7/dist-packages/director/mainwindowapp.py", line 2, in <module>
    from director.componentgraph import ComponentFactory
  File "/home/gearsad/.julia/v0.5/DrakeVisualizer/deps/usr/lib/python2.7/dist-packages/director/componentgraph.py", line 2, in <module>
    from director.fieldcontainer import FieldContainer
  File "/home/gearsad/.julia/v0.5/DrakeVisualizer/deps/usr/lib/python2.7/dist-packages/director/fieldcontainer.py", line 2, in <module>
    import numpy as np
ImportError: No module named numpy
```

I'm running ubuntu 16.04 with Julia details below:

```julia

Julia Version 0.5.0

Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
```

**Comment by rdeits** [comment]
Thanks for reporting this. This might be an issue with the binary packaging over at https://github.com/RobotLocomotion/director/issues/470

**Comment by rdeits** [comment]
Does doing `sudo apt-get install python-numpy` resolve the issue?

**Comment by dehann** [comment]
Hi, sorry yes we were able to resolve the issue by installing numpy. I think @GearsAD did it via pip install?

**Comment by rdeits** [comment]
Ok, great! I've updated the documentation.

**Comment by GearsAD** [comment]
Sorry didn't see the notifications. Yes was a pip install if I recall correctly. 

Thanks!
